# -*- coding: utf-8 -*-
"""Упражнение 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1455XymtB8jbZudhETOfOSm_VwIwCHbZ4
"""

